### ISSUE TITLE
WinRAR for ARM

### ISSUE THREAD

**Issue by JorricksTU** [matiasb/python-unrar#12]
Hello Matiasb,

I'm trying to get your package to work after testing it out on a virtual machine.
It works very well on my virtual machine but it does not work at all with my armv7 (odroid).
My error is  
`
OSError: /usr/local/src/python-unrar-master/dependencies/unrar/libunrar.so: wrong ELF class: ELFCLASS64
`
This is after that I used
`make lib
make install-lib`
and added the UNRAR_LIB_PATH variable. Is there something that I'm doing wrong?

**Comment by JorricksTU** [comment]
So after spending an hour trying this stuff with using the original installation guide and the ubuntu guide as seen here 
https://help.ubuntu.com/community/CompilingEasyHowTo
The 10th time running the last installation worked somehow.
Please set this as closed :)

**Comment by matiasb** [comment]
Awesome, good to know you got it working. If you have any comments to add to improve the instructions, let me know. Closing for now.
